version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
      - ./data:/data
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
    restart: unless-stopped
    networks:
      - soundtracker-network

  # Add other services like databases here if needed
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - soundtracker-network

networks:
  soundtracker-network:
    driver: bridge

# volumes:
#   redis_data:
#     driver: local
